=== lruizap/1-DAW-Markup_Lnaguage/XML/T03/nota.dtd
<!ELEMENT nota (de, para+, asunto, tema, (test? | test2))>
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT tema (#PCDATA)>

<!ELEMENT test ANY>
<!ELEMENT test2 ANY>

<!-- ? opcional - 1 o ninguno -->
<!-- + 1 o más -->
<!-- * ninguno o más -->
<!-- | uno u otro -->

=== lruizap/1-DAW-Markup_Lnaguage/XML/T03/nota.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nota SYSTEM "nota.dtd">
<nota>
    <de>Ana</de>
    <para>Alfredo</para>
    <para>Luis</para>
    <para>Fernando</para>
    <asunto>Reuni√≥n a las 15:00</asunto>
    <tema>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime hic placeat corrupti quidem autem omnis voluptate, tempora possimus voluptatem soluta error mollitia aperiam quo, nesciunt saepe, tenetur modi nihil velit?</tema>
    
    <test>
        <de></de>
        <para></para>
    </test>

    <!-- <test2>
        
    </test2> -->

</nota>
