=== lruizap/1-DAW-Markup_Lnaguage/XML/Estudiar/2/2.dtd
<!ELEMENT tablon (anuncio+)>

    <!-- , secuencia obligatoria de elementos
            +   almenos 1
            *   cero o más
            ?   cero o una, elemento opcional
            |   una u otra
    -->

    <!ELEMENT anuncio (fecha,asunto,texto?,precio,(contacto|telefono)+,fechaLimite?,localiza,vacio)>

    <!-- ATTLIST = nombreElemento nombreAtributo tipoAtributo valorPorDefecto -->

    <!-- Valor Atributos :
                    #REQUIRED => OBLIGATORIO
                    #IMPLIED => OPCIONAL
                    #FIXED "VALOR" => VALOR CONSTANTE
                    (VALOR1 | VALOR2) => ENUMAERADO
    -->

    <!-- Tipos de attuto
            CDATA -> CUALQUIER CARÁCTER
            NMTOKEN -> SOLO LETRAS, DÍGITOS, ., -, _, :
            NMTOKENS -> LOS MISMOS QUE NMTOKEN + ESPACIOS EN BLANCO, TAB ...
            ID -> 
                    DEBE COMENZAR CON 1 LETRA
                    SOLO CARÁCTERES VÁLIDFOS EN NMTOKEN
                    1 ELEMENTO SOLO 1 ATRIBUTO ID
                    ID DEBE TENER UN VALOR QUE NO SE REPITA INCLUSO ENTREETROS ATRIBUTOS DEL TIPO ID
            IDREF -> CORRESPONDE CON EL VALOR DE ALGÚN ATRIBUTO ID DEL DOCUMENTO
            IDREFS -> PUEDE CONTENER VARIAS REFERENCIAS A ELEMENTOS CON ATRIBUTOS ID SEPARADOS POR ESPACIOS EN BLANCO
    -->

    <!-- 3 atributos para 1 elemento -->

    <!ATTLIST anuncio vendido (Si|No) #REQUIRED>
    <!ATTLIST anuncio lang CDATA #FIXED "ESP">
    <!ATTLIST anuncio codigo ID #REQUIRED>

    <!-- Cuando hay más de un atributo para un elemento se puede poner de la siguiente forma

        <!ATTLIST anuncio vendido (Si|No) #REQUIRED
                        lang CDATA #FIXED "ESP"
                        codigo ID #REQUIRED> 
    -->

        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT asunto (#PCDATA)>
        <!ELEMENT texto (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ATTLIST precio Moneda_Pago NMTOKEN #IMPLIED>
        <!ELEMENT contacto (nombre, telefono)>
        <!ATTLIST contacto visible (Si|No) #REQUIRED>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT fechaLimite (#PCDATA)>
        <!ELEMENT localiza (#PCDATA)>
        <!ELEMENT vacio EMPTY>

        <!-- & < > ==> &amp; &lt; &gt; -->

=== lruizap/1-DAW-Markup_Lnaguage/XML/Estudiar/2/2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tablon SYSTEM "2.dtd">

<tablon>
    <anuncio codigo="A-001" vendido="No" lang="ESP">
        <fecha>2022/03/20</fecha>
        <asunto>Vendo Patinete</asunto>
        <texto>Vendo Patinete Seminuevo</texto>
        <precio Moneda_Pago="Euros">50</precio>
        <contacto visible="Si">
            <nombre>Juan Jose</nombre>
            <telefono>344334333</telefono>
        </contacto>
        <contacto visible="No">
            <nombre>Paco</nombre>
            <telefono>555666555</telefono>
        </contacto>
        <fechaLimite>2023/01/01</fechaLimite>
        <localiza>Madrid</localiza>
        <vacio />
    </anuncio>

    <anuncio codigo="B-001" vendido="Si" lang="ESP">
        <fecha>2019/12/15</fecha>
        <asunto>Vendo Bici</asunto>
        <precio>100</precio>
        <contacto visible="Si">
            <nombre>Antonio</nombre>
            <telefono>121223222</telefono>
        </contacto>
        <localiza>Gibraltar</localiza>
        <vacio />
    </anuncio>
</tablon>
