=== lruizap/1-DAW-Markup_Lnaguage/XML/T03/Clase/clase.dtd
<!ELEMENT clase (modulos, alumnado)>
<!ELEMENT modulos (nombre+)>

    <!ELEMENT nombre (#PCDATA)>
    <!ATTLIST nombre id ID #REQUIRED>

<!ELEMENT alumnado (Datos+)>

    <!ELEMENT Datos (#PCDATA)>
    <!ATTLIST Datos modulos IDREF #REQUIRED>

=== lruizap/1-DAW-Markup_Lnaguage/XML/T03/Clase/clase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clase SYSTEM "clase.dtd">

<clase>
    <modulos>
        <nombre id="M01">LMSGI</nombre>
        <nombre id="M02">Base de Datos</nombre>
        <nombre id="M03">Programaci√≥n</nombre>
        <nombre id="M04">Entornos de Desarrollo</nombre>
    </modulos>
    <alumnado>
        <Datos modulos="M02">Alfredo</Datos>
        <Datos modulos="M03">Paco</Datos>
        <Datos modulos="M01"></Datos>
    </alumnado>
</clase>
